Cybits Chain to Blockcore-Hub
block-core/blockcore-desktop pull request #35
Opened 2022-02-04 20:29 UTC by psavva

This PR add the Cybits chain to the blockcore-hub

2022-02-04 20:30 UTC, psavva commented
There is also an improvement to the background alignment - centre when changing screen sizes.

2022-02-04 22:00 UTC, sondreb requested changes
Thanks for the PR, please look at the capitalization of root folder name.

2022-02-04 22:00 UTC, sondreb commented on src/app/services/chain.service.ts
> +                { opreturndata: 80, pos: true, rootFolderName: 'Cybits', test: false, name: 'Cybits Main', chain: 'Cybits', private: 160, public: 28, identity: 'Cybits', tooltip: 'Cybits', port: 1777
Are you sure the root folder name is with capital C? It must be correct casing or fails on Linux.

2022-02-04 22:00 UTC, sondreb commented on src/app/services/chain.service.ts
> +                { opreturndata: 80, pos: true, rootFolderName: 'Cybits', test: false, name: 'Cybits Main', chain: 'Cybits', private: 160, public: 28, identity: 'Cybits', tooltip: 'Cybits', port: 1777
Don't call the mainnet for "Main" this is displayed to users.

2022-02-05 06:24 UTC, psavva commented
Good Morning @sondreb 
Changes have been incorporated.

2022-02-05 06:24 UTC, psavva commented on src/app/services/chain.service.ts
> +                { opreturndata: 80, pos: true, rootFolderName: 'Cybits', test: false, name: 'Cybits Main', chain: 'Cybits', private: 160, public: 28, identity: 'Cybits', tooltip: 'Cybits', port: 1777
Done.

2022-02-05 11:10 UTC, sondreb approved these changes
Thanks for the PR!

2022-02-05 11:10 UTC, merged